[versions]
# This project version
bigbone = "2.0.0-SNAPSHOT"

# 3rd party dependencies
junit-jupiter = "5.11.4"
junit-platform-suite-engine = "1.11.4"
junit-platform-launcher = "1.11.4"
kluent = "1.73"
kotlin = "2.1.0"
kotlin-coroutines = "1.10.1"
kotlinx-serialization-json = "1.8.0"
mockk = "1.13.16"
okhttp = "5.0.0-alpha.14"
rxjava = "3.1.10"

# Gradle plugins
jacoco = "0.8.9"
dependency-analysis = "2.7.0"
detekt = "1.23.6"
versions = "0.52.0"
ktlint = "12.1.2"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junit-platform-suite-engine" }
kluent = { module = "org.amshove.kluent:kluent", version.ref = "kluent" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
