version: '3.8'

services:
  mastodon-base:
    image: 'tootsuite/mastodon'
    environment:
      RAILS_ENV: 'production'
      LOCAL_DOMAIN: '${MASTODON_DOMAIN}'
      REDIS_HOST: 'mastodon-redis' # name of the redis container
      DB_HOST: 'mastodon-db' # name of the database container
      DB_NAME: '${MASTODON_POSTGRES_DATABASE}'
      DB_USER: '${MASTODON_POSTGRES_USERNAME}'
      DB_PASS: '${MASTODON_POSTGRES_PASSWORD}'
      SECRET_KEY_BASE: '${MASTODON_SECRET_KEY_BASE}'
      OTP_SECRET: '${MASTODON_OTP_SECRET}'
      SMTP_SERVER: '${SMTP_SERVER}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_LOGIN: '${SMTP_LOGIN}'
      SMTP_PASSWORD: '${SMTP_PASSWORD}'
      SMTP_FROM_ADDRESS: '${SMTP_FROM_ADDRESS}'
      ES_ENABLED: 'true'
      ES_HOST: 'mastodon-es' # name of the elasticsearch container
      VAPID_PRIVATE_KEY: '${MASTODON_VAPID_PRIVATE_KEY}'
      VAPID_PUBLIC_KEY: '${MASTODON_VAPID_PUBLIC_KEY}'
      S3_ENABLED: 'false'
      S3_PROTOCOL: 'https'
      S3_ENDPOINT: '${MASTODON_S3_ENDPOINT}'
      S3_HOSTNAME: '${MASTODON_S3_HOSTNAME}'
      S3_REGION: '${MASTODON_S3_REGION}'
      S3_BUCKET: '${MASTODON_S3_BUCKET}'
      AWS_ACCESS_KEY_ID: '${MASTODON_S3_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${MASTODON_S3_SECRET_ACCESS_KEY}'
      S3_ALIAS_HOST: '${MASTODON_S3_DOMAIN}'
