title: BigBone
description: A Mastodon Client Library for Java and Kotlin
remote_theme: just-the-docs/just-the-docs
aux_links:
  GitHub Repo: https://github.com/andregasser/bigbone
aux_links_new_tab: true
heading_anchors: true
color_scheme: light